2015-05-15 18:50:08,098 INFO  [main] util.VersionInfo: HBase 0.98.12-hadoop1
2015-05-15 18:50:08,123 INFO  [main] util.VersionInfo: Subversion git://aspire/home/apurtell/src/hbase -r bbf8bf4362e858bd9bd0511c9289c31b09b7a927
2015-05-15 18:50:08,123 INFO  [main] util.VersionInfo: Compiled by apurtell on Thu Apr  9 18:55:45 PDT 2015
2015-05-15 18:50:10,587 INFO  [main] zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x2a901849 connecting to ZooKeeper ensemble=HBNode1:2181,HB:2181,HBNode2:2181
2015-05-15 18:50:10,728 INFO  [main] zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:host.name=HB
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.version=1.7.0_79
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-7-openjdk-amd64/jre
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.class.path=/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../conf:/usr/lib/tools.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/..:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/activation-1.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/asm-3.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-beanutils-1.7.0.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-beanutils-core-1.8.0.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-cli-1.2.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-codec-1.7.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-collections-3.2.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-configuration-1.6.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-digester-1.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-el-1.0.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-httpclient-3.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-io-2.4.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-lang-2.6.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-logging-1.1.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-math-2.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/commons-net-1.4.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/findbugs-annotations-1.3.9-1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/guava-12.0.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hadoop-core-1.2.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hamcrest-core-1.3.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-annotations-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-checkstyle-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-client-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-common-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-common-0.98.12-hadoop1-tests.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-examples-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-hadoop1-compat-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-hadoop-compat-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-it-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-it-0.98.12-hadoop1-tests.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-prefix-tree-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-protocol-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-rest-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-server-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-server-0.98.12-hadoop1-tests.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-shell-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-testing-util-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/hbase-thrift-0.98.12-hadoop1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/HelloCoprocessor.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/high-scale-lib-1.1.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/htrace-core-2.04.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/httpclient-4.1.3.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/httpcore-4.1.3.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-core-asl-1.8.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-jaxrs-1.8.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-mapper-asl-1.8.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jackson-xc-1.8.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jamon-runtime-2.3.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jasper-compiler-5.5.23.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jasper-runtime-5.5.23.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jaxb-api-2.2.2.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jaxb-impl-2.2.3-1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jcodings-1.0.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-client-1.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-core-1.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-json-1.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jersey-server-1.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jettison-1.3.1.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jetty-6.1.26.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jetty-sslengine-6.1.26.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jetty-util-6.1.26.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/joni-2.1.2.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jruby-complete-1.6.8.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jsp-2.1-6.1.14.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jsp-api-2.1-6.1.14.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/jsr305-1.3.9.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/junit-4.11.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/libthrift-0.9.0.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/log4j-1.2.17.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/metrics-core-2.2.0.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/netty-3.6.6.Final.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/protobuf-java-2.5.0.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/servlet-api-2.5-6.1.14.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/slf4j-api-1.6.4.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/slf4j-log4j12-1.6.4.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/xmlenc-0.52.jar:/home/jeff/Documents/hbase-0.98.12-hadoop1/bin/../lib/zookeeper-3.4.6.jar::/home/jeff/Documents/hbase-0.98.12-hadoop1/lib/HelloCoprocessor.jar
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
2015-05-15 18:50:10,729 INFO  [main] zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
2015-05-15 18:50:10,730 INFO  [main] zookeeper.ZooKeeper: Client environment:os.name=Linux
2015-05-15 18:50:10,730 INFO  [main] zookeeper.ZooKeeper: Client environment:os.arch=amd64
2015-05-15 18:50:10,730 INFO  [main] zookeeper.ZooKeeper: Client environment:os.version=3.16.0-30-generic
2015-05-15 18:50:10,730 INFO  [main] zookeeper.ZooKeeper: Client environment:user.name=jeff
2015-05-15 18:50:10,730 INFO  [main] zookeeper.ZooKeeper: Client environment:user.home=/home/jeff
2015-05-15 18:50:10,730 INFO  [main] zookeeper.ZooKeeper: Client environment:user.dir=/home/jeff/Documents/hbase-0.98.12-hadoop1
2015-05-15 18:50:10,744 INFO  [main] zookeeper.ZooKeeper: Initiating client connection, connectString=HBNode1:2181,HB:2181,HBNode2:2181 sessionTimeout=90000 watcher=hconnection-0x2a9018490x0, quorum=HBNode1:2181,HB:2181,HBNode2:2181, baseZNode=/hbase
2015-05-15 18:50:11,125 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:11,268 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Socket connection established to HBNode1/10.0.2.5:2181, initiating session
2015-05-15 18:50:11,400 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server HBNode1/10.0.2.5:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:11,600 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2015-05-15 18:50:11,600 INFO  [main] util.RetryCounter: Sleeping 1000ms before retry #0...
2015-05-15 18:50:11,772 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:11,774 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Socket connection established to HB/10.0.2.4:2181, initiating session
2015-05-15 18:50:12,162 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server HB/10.0.2.4:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:13,009 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:13,010 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:13,125 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2015-05-15 18:50:13,125 INFO  [main] util.RetryCounter: Sleeping 2000ms before retry #1...
2015-05-15 18:50:14,908 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:14,909 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:15,819 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:15,819 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:15,922 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2015-05-15 18:50:15,922 INFO  [main] util.RetryCounter: Sleeping 4000ms before retry #2...
2015-05-15 18:50:16,538 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:16,540 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:17,812 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:17,813 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:18,864 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:18,865 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:19,408 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:19,409 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:20,911 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:20,912 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:21,013 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2015-05-15 18:50:21,013 INFO  [main] util.RetryCounter: Sleeping 8000ms before retry #3...
2015-05-15 18:50:21,620 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:21,620 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:22,212 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:22,213 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:23,452 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:23,453 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:23,717 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:23,717 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:24,294 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:24,296 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:26,366 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:26,367 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:26,601 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:26,602 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:27,395 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:27,396 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:29,005 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:29,006 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:29,107 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2015-05-15 18:50:29,107 ERROR [main] zookeeper.RecoverableZooKeeper: ZooKeeper exists failed after 4 attempts
2015-05-15 18:50:29,107 WARN  [main] zookeeper.ZKUtil: hconnection-0x2a9018490x0, quorum=HBNode1:2181,HB:2181,HBNode2:2181, baseZNode=/hbase Unable to set watcher on znode (/hbase/hbaseid)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:907)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:701)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:457)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:436)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:317)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:194)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:216)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-05-15 18:50:29,111 ERROR [main] zookeeper.ZooKeeperWatcher: hconnection-0x2a9018490x0, quorum=HBNode1:2181,HB:2181,HBNode2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:907)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:701)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:457)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:436)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:317)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:194)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:216)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-05-15 18:50:29,112 WARN  [main] client.ZooKeeperRegistry: Can't retrieve clusterId from Zookeeper
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:907)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:701)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:457)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:436)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:317)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:194)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:216)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-05-15 18:50:29,113 DEBUG [main] client.HConnectionManager$HConnectionImplementation: clusterid came back null, using default default-cluster
2015-05-15 18:50:29,830 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:29,830 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:29,931 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-05-15 18:50:29,932 INFO  [main] util.RetryCounter: Sleeping 1000ms before retry #0...
2015-05-15 18:50:30,055 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:30,056 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:31,800 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:31,801 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:31,903 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-05-15 18:50:31,903 INFO  [main] util.RetryCounter: Sleeping 2000ms before retry #1...
2015-05-15 18:50:32,802 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:32,802 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:33,132 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:33,139 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:34,975 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:34,989 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:35,089 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-05-15 18:50:35,090 INFO  [main] util.RetryCounter: Sleeping 4000ms before retry #2...
2015-05-15 18:50:35,476 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:35,477 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:36,160 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:36,161 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:37,515 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:37,538 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:38,231 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:38,232 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:38,861 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:38,862 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:40,351 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:40,353 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:40,453 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-05-15 18:50:40,453 INFO  [main] util.RetryCounter: Sleeping 8000ms before retry #3...
2015-05-15 18:50:40,584 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:40,585 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:41,273 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:41,288 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:42,679 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:42,687 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:43,124 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:43,125 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:43,301 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:43,302 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:45,139 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:45,140 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:45,684 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:45,684 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:46,370 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:46,387 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:47,604 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:47,607 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:47,832 INFO  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Opening socket connection to server HB/10.0.2.4:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:47,833 WARN  [main-SendThread(HB:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:48,252 INFO  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode2/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:48,253 WARN  [main-SendThread(HBNode2:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:50,263 INFO  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Opening socket connection to server HBNode1/10.0.2.5:2181. Will not attempt to authenticate using SASL (unknown error)
2015-05-15 18:50:50,264 WARN  [main-SendThread(HBNode1:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-05-15 18:50:50,365 WARN  [main] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=HBNode1:2181,HB:2181,HBNode2:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
2015-05-15 18:50:50,365 ERROR [main] zookeeper.RecoverableZooKeeper: ZooKeeper exists failed after 4 attempts
2015-05-15 18:50:50,366 WARN  [main] zookeeper.ZKUtil: hconnection-0x2a9018490x0, quorum=HBNode1:2181,HB:2181,HBNode2:2181, baseZNode=/hbase Unable to set watcher on znode (/hbase)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-05-15 18:50:50,366 ERROR [main] zookeeper.ZooKeeperWatcher: hconnection-0x2a9018490x0, quorum=HBNode1:2181,HB:2181,HBNode2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
2015-05-15 18:50:50,368 ERROR [main] client.HConnectionManager$HConnectionImplementation: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
2015-05-15 18:50:50,368 INFO  [main] client.HConnectionManager$HConnectionImplementation: getMaster attempt 1 of 1 failed; no more retrying.
org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:934)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	... 15 more
2015-05-15 18:50:50,376 ERROR [main] master.HMasterCommandLine: Failed to stop master
org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=1, exceptions:
Fri May 15 18:50:50 CEST 2015, org.apache.hadoop.hbase.client.RpcRetryingCaller@19ca276f, org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase

	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:131)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:91)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3399)
	at org.apache.hadoop.hbase.client.HBaseAdmin.shutdown(HBaseAdmin.java:2153)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.stopMaster(HMasterCommandLine.java:228)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3029)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1698)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1724)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1931)
	at org.apache.hadoop.hbase.client.HBaseAdmin$MasterCallable.prepare(HBaseAdmin.java:3372)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
	... 8 more
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:934)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:597)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1624)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1670)
	... 12 more
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:222)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:923)
	... 15 more
